version: '3'

services:
  php-fpm:
    build:
      context: ./docker/php-fpm

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./src/:/var/www
      - ./docker/nginx/config:/etc/nginx
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8088:80"
      - "443:443"
    depends_on:
      - php-fpm

  database:
    build:
      context: ./docker/database
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./docker/database/data.sql:/docker-entrypoint-initdb.d/data.sql